### ISSUE TITLE
Remove/Merge old specifications - Delete/Move non user facing technical specifications

### ISSUE THREAD

**Issue by gmourier** [meilisearch/specifications#216]
Some technical specifications do not concern any direct user-facing aspect and could be deleted or moved to a specific folder.

We also have old specifications that have the old format (they describe changes at the moment the specification file was made).

Most of them could be cleaned up to have the new format and some could be removed because they are split in the API routes that describe the usage of this feature. e.g (https://github.com/meilisearch/specifications/issues/130)

**Comment by gmourier** [comment]
Partially fixed by https://github.com/meilisearch/specifications/pull/233

**Comment by curquiza** [comment]
Closing this since this repo will be archived, so not relevant anymore
